# Generated by Django 3.2 on 2021-04-10 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailInfo',
            fields=[
                ('update_user', models.CharField(max_length=45)),
                ('create_user', models.CharField(max_length=45)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('code', models.TextField()),
                ('style', models.IntegerField()),
                ('status', models.IntegerField()),
                ('notes', models.TextField()),
            ],
            options={
                'db_table': 'question_detail',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('update_user', models.CharField(max_length=45)),
                ('create_user', models.CharField(max_length=45)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('type', models.IntegerField()),
                ('status', models.IntegerField()),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'question_bank',
            },
        ),
        migrations.CreateModel(
            name='QuestionDetailRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_detail_id', to='bank.detailinfo')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_question_id', to='bank.questions')),
            ],
            options={
                'db_table': 'question_detail_rel',
            },
        ),
    ]
